"use client";
import { useState } from "react";
import Link from "next/link";
const steps = [
  { title: "Reúna a vila", icon: "⌂", heading: "Os amigos chegam. Os segredos também.", text: "Crie uma sala e compartilhe o código com 4 a 8 pessoas. Cada uma entra no próprio navegador, escolhe um nome e um retrato e confirma que está pronta.", note: "Conversem pelo chat da sala, presencialmente ou em uma chamada de voz. O jogo conduz as cenas por texto.", tag: "ANTES DA PARTIDA" },
  { title: "Receba seu papel", icon: "◇", heading: "Sua foto é pública. Sua missão, secreta.", text: "O jogo sorteia os papéis: assassino, xerife, anjo e cidadãos. O assassino vence quando resta no máximo um outro morador vivo. Os demais vencem ao descobri-lo e eliminá-lo.", note: "Xerife: investiga uma pessoa. Anjo: protege uma pessoa. Cidadão: observa, debate e vota.", tag: "SÓ VOCÊ PODE VER" },
  { title: "Atravesse a noite", icon: "☾", heading: "As luzes se apagam. Alguém age.", text: "Assassino, xerife e anjo escolhem seus alvos em segredo. Cidadãos aguardam. O narrador resolve as ações e conta o que aconteceu quando amanhece.", note: "O tempo da cena aparece na tela. As ações são registradas pelo jogo e a rodada avança automaticamente.", tag: "AÇÕES EM SEGREDO" },
  { title: "Converse e decida", icon: "☼", heading: "O dia traz perguntas. Nem sempre respostas.", text: "Debatam as pistas e as versões durante a discussão. Depois, cada pessoa viva vota em um suspeito ou se abstém. Quem recebe mais votos é eliminado; empate não elimina ninguém.", note: "O jogo anuncia o resultado. Uma nova noite começa até a vitória da vila ou do assassino.", tag: "SUSPEITA, VOTO E CONSEQUÊNCIA" },
];
export function HowToPlay() {
  const [step, setStep] = useState(0);
  const current = steps[step];
  return <section className="page-shell rules-page"><header className="page-heading"><div><p className="eyebrow">UM PEQUENO GUIA PARA SOBREVIVER</p><h1>A vila tem <em>suas regras.</em></h1></div><p>Quatro passos. Muitas versões da verdade.<br />O narrador cuida do ritmo da partida.</p></header>
    <div className="rules-layout"><div className="step-list" role="tablist" aria-label="Etapas do jogo">{steps.map((s, i) => <button role="tab" aria-selected={step === i} tabIndex={step === i ? 0 : -1} onKeyDown={event => { let next = i; if (event.key === "ArrowRight" || event.key === "ArrowDown") next = (i + 1) % steps.length; else if (event.key === "ArrowLeft" || event.key === "ArrowUp") next = (i + steps.length - 1) % steps.length; else if (event.key === "Home") next = 0; else if (event.key === "End") next = steps.length - 1; else return; event.preventDefault(); setStep(next); document.getElementById(`step-${next}`)?.focus(); }} aria-controls="step-content" id={`step-${i}`} key={s.title} onClick={() => setStep(i)} className={step === i ? "active" : ""}><span>0{i + 1}</span><strong>{s.title}</strong><span aria-hidden="true">↗</span></button>)}</div><article className="rule-panel" id="step-content" role="tabpanel" aria-labelledby={`step-${step}`}><span className="rule-symbol" aria-hidden="true">{current.icon}</span><p className="eyebrow">{current.tag}</p><h2>{current.heading}</h2><p>{current.text}</p><div className="rule-note">{current.note}</div><div className="rule-footer"><span>0{step + 1} <span className="muted">/ 04</span></span>{step < 3 ? <button className="button button-secondary" onClick={() => setStep(step + 1)}>Próximo passo →</button> : <Link className="button button-primary" href="/entrar?modo=criar">Criar minha sala ↗</Link>}</div></article></div>
  </section>;
}
